service: software-chatter-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  stage: dev
  region: eu-west-1
  profile: kendi-hesabim
  tracing:
    lambda: true
  
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 60

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource: '*'

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
        - aws-sdk
    platform: 'node'
    concurrency: 10
    plugins: ./esbuild-plugins.js

resources:
  Resources:
    tweetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cihan-software-chatter-backend-bucket

functions:
  crawler:
    handler: src/lambda.handler
    timeout: 300
    environment:
      BUCKET: ${self:resources.Resources.tweetsBucket.Properties.BucketName}
      TWITTER_APP_KEY: ${env:TWITTER_APP_KEY}
      TWITTER_APP_SECRET: ${env:TWITTER_APP_SECRET}
      TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${env:TWITTER_ACCESS_SECRET}
      TWITTER_BEARER_TOKEN: ${env:TWITTER_BEARER_TOKEN}
